### ISSUE TITLE
feature request: database collection prefix

### ISSUE THREAD

**Issue by ericvrp** [iaincollins/next-auth-example#3]
I am using mongodb. There are 4 collections created (account,email_verification,session and user). Is there an option where I set the prefix for all NextAuth collections/tables to something like nextauth_account, nextauth_email_verification.... ?

**Comment by iaincollins** [comment]
I think that's a great idea, and is actually a feature I need myself so I'm quite motivated to add it.

The cookies are named with a prefix so they don't collide with any existing site cookies - and so that their purpose is clear - and I think there is a good case for doing same with the database tables (and making it configurable so people can set them to be blank, or something custom).

The [next-auth](https://github.com/iaincollins/next-auth/issues/) repo would be  a good place to raise this!

**Comment by iaincollins** [comment]
PS: Does it seem to be working in mongodb for you? About to get round to formal testing of v2 now API is pretty stable, but am interested in anecdotal reports of DB compatibility.

**Comment by ericvrp** [comment]
Alright. I forgot that the example was not in the next-auth repo. I got confused about the layout of the repo before. I couldn't find a clear location or a v2 branch and I couldn't find beta version releases/tags. Almost gave up :-)

Yes it seems to be working but I did not proper testing yet. Just no more error messages.

sqlite needs some love to get installable without any additional help. I work on Windows and deploy to Linux most often so cross platform support is something I need. But sqlite I can live without.

anecdotal reports :-)

**Comment by ericvrp** [comment]
Added: https://github.com/iaincollins/next-auth/issues/140
Perhaps close this one if you like?

**Comment by iaincollins** [comment]
Great, thank you for raising that and for the info.

PS: In v1 the example was in the parent repo, with v2 I've split it off as there are technical issues that can arise from an example and a client that uses it being in the same repo, due to the way NPM (and, IIRC Babel and/or Webpack) work that can make it hard to debug issues (and easy to miss problems).

The plan is that this example will be improved and cleaned up and will use GitHub actions CD/CI flow to automatically update it with the latest release, and run automated tests tests against it (in a live environment).
